language: cpp

common_sources: &all_sources
  - ubuntu-toolchain-r-test
  - llvm-toolchain-trusty
  - llvm-toolchain-trusty-6.0
  - llvm-toolchain-trusty-7

matrix:
  include:
    #- os: linux
    #  compiler: gcc
    #  addons: &gcc8
    #    apt:
    #      sources: *all_sources
    #      packages: ['g++-8']
    #  env: COMPILER='g++-8'

    # 1/ Linux Clang Builds
    - os: linux
      compiler: clang
      addons:
          apt:
              sources: *all_sources
              packages: ['clang-7']
      env: COMPILER='clang++-7'

before_script:
  - export CXX=${COMPILER}
  - mkdir build
  - cd build
  - cmake ..

script: make && make test