language: cpp

matrix:
  include:
    # 1/ Linux GCC Builds
    - os: linux
      dist: xenial
      #compiler: gcc
      addons: 
        apt:
          sources: 
            - ubuntu-toolchain-r-test
          packages: 
            - g++-7
      env: MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: linux
      dist: xenial
      #compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env: MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

    # 2/ Linux Clang Builds
    - os: linux
      dist: xenial
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"

before_install:
  - eval "${MATRIX_EVAL}"

before_script:
  #- export CXX=${COMPILER}
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug

script: 
  - cmake --build . --target all -v -- -j6 
  - ctest .