name: C/C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: g++
      run: g++ --version
    - name: cmake
      run: cmake --version
    - name: pwd
      run: pwd
